; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP32 GPS Navigator
default_envs = ESP32S3_N16R8

[common]
platform = espressif32@6.9.0
framework = arduino
version = 0.2.0
revision = 84
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = 
  esp32_exception_decoder
  printable
build_flags = 
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
  -DESP_LOG_LEVEL=ESP_LOG_WARN
  -DESP_LOG_LEVEL_MAIN=ESP_LOG_VERBOSE
  -D DISABLE_RADIO=1
  -D BAUDRATE=115200
  -D DEBUG=1

lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    bitbank2/PNGdec@^1.0.3
    celliesprojects/OpenStreetMap-esp32
    mikalhart/TinyGPSPlus@^1.0.3
    bblanchon/ArduinoJson@^6.21.3
    paulstoffregen/Time@^1.6.1

[esp32_common]
extends = common

[env:ESP32S3_N16R8]
extends = esp32_common
board = esp32-s3-devkitc-1-n16r8v
board_build.flash_mode = dio  ; Explicitly set flash mode
board_build.partitions = default_16MB.csv
lib_deps =
  ${common.lib_deps}
build_flags =
  ${common.build_flags}
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DARDUINO_USB_MODE=1
  -std=gnu++17
build_unflags = 
  -std=gnu++11  ; Prevent conflicts
  -std=gnu++10  ; Prevent conflicts
